/**
 * Convex Client Configuration
 * React hooks and client setup for Convex
 */

"use client";

import { ConvexReactClient } from "convex/react";
import { useQuery, useMutation, useAction } from "convex/react";
import type { FunctionReference, OptionalRestArgs } from "convex/server";

// ============================================================================
// Convex Client
// ============================================================================

const convexUrl = process.env.NEXT_PUBLIC_CONVEX_URL;

if (!convexUrl) {
  console.warn("NEXT_PUBLIC_CONVEX_URL is not set. Convex features will be disabled.");
}

export const convex = new ConvexReactClient(convexUrl ?? "");

// ============================================================================
// Typed Hooks
// ============================================================================

/**
 * Type-safe wrapper for useQuery
 */
export function useConvexQuery<Query extends FunctionReference<"query">>(
  query: Query,
  ...args: OptionalRestArgs<Query>
) {
  return useQuery(query, ...args);
}

/**
 * Type-safe wrapper for useMutation
 */
export function useConvexMutation<Mutation extends FunctionReference<"mutation">>(
  mutation: Mutation
) {
  return useMutation(mutation);
}

/**
 * Type-safe wrapper for useAction
 */
export function useConvexAction<Action extends FunctionReference<"action">>(
  action: Action
) {
  return useAction(action);
}

// ============================================================================
// Real-time Subscription Helpers
// ============================================================================

/**
 * Helper for creating optimistic updates
 */
export function createOptimisticUpdate<T>(
  currentData: T | undefined,
  updateFn: (data: T) => T
): T | undefined {
  if (!currentData) return undefined;
  return updateFn(currentData);
}

// ============================================================================
// Convex API Types (generated from schema)
// ============================================================================

// These types would normally be generated by Convex CLI
// For now, we define the expected structure

export interface ConvexUser {
  _id: string;
  _creationTime: number;
  email: string;
  name?: string;
  avatar?: string;
  kycStatus: "pending" | "approved" | "rejected" | "needs_review";
  kycTier: "basic" | "enhanced" | "accredited";
  walletAddress?: string;
  referralCode?: string;
  emailVerified: boolean;
}

export interface ConvexBalance {
  _id: string;
  _creationTime: number;
  userId: string;
  asset: string;
  available: number;
  held: number;
  pending: number;
}

export interface ConvexOrder {
  _id: string;
  _creationTime: number;
  userId: string;
  marketId: string;
  side: "buy" | "sell";
  orderType: "market" | "limit";
  quantity: number;
  price?: number;
  status: "pending" | "open" | "filled" | "partially_filled" | "cancelled" | "rejected";
  filledQuantity: number;
  averagePrice?: number;
}

export interface ConvexPosition {
  _id: string;
  _creationTime: number;
  userId: string;
  marketId: string;
  outcome: string;
  quantity: number;
  averagePrice: number;
  realizedPnl: number;
}

export interface ConvexPredictionEvent {
  _id: string;
  _creationTime: number;
  externalId: string;
  title: string;
  description: string;
  category: string;
  status: "upcoming" | "active" | "closed" | "settled";
  closesAt: number;
  settlesAt?: number;
  outcome?: string;
  imageUrl?: string;
}

export interface ConvexRWAAsset {
  _id: string;
  _creationTime: number;
  assetType: "pokemon_card" | "sports_card" | "collectible";
  name: string;
  description: string;
  imageUrl: string;
  grade: number;
  gradingCompany: "PSA" | "BGS" | "CGC";
  certNumber: string;
  currentPrice: number;
  totalShares: number;
  availableShares: number;
  ownerId: string;
}

export interface ConvexEmail {
  _id: string;
  _creationTime: number;
  userId: string;
  externalId: string;
  from: string;
  to: string[];
  subject: string;
  body: string;
  snippet: string;
  receivedAt: number;
  isRead: boolean;
  isArchived: boolean;
  triagePriority?: "urgent" | "important" | "normal" | "low";
  triageCategory?: string;
  triageSummary?: string;
}

export interface ConvexMatrixRoom {
  _id: string;
  _creationTime: number;
  roomId: string;
  name: string;
  roomType: "dm" | "group" | "channel";
  members: string[];
  createdBy: string;
  lastMessageAt?: number;
  unreadCount?: number;
}

export interface ConvexPointsBalance {
  _id: string;
  _creationTime: number;
  userId: string;
  available: number;
  lifetime: number;
  tier: "bronze" | "silver" | "gold" | "platinum" | "diamond";
  currentStreak: number;
  longestStreak: number;
}
